Create UI for profile photo
hatchways/team-watermint pull request #59
Opened 2022-02-05 19:24 UTC by EdwardOlmos

### What this PR does (required):
- Resolves #24
- Adds ProfilePhoto page and styling for route /profile/settings/profile-photo

### Screenshots / Videos (front-end only):
- User with a default profile photo
<img width="838" alt="default_view" src="https://user-images.githubusercontent.com/18078583/152598740-e2ef85e4-06f3-4cb8-875d-2bc47a6a89c0.png">

- User with a custom profile photo
<img width="838" alt="user_profile_photo" src="https://user-images.githubusercontent.com/18078583/152598767-ec4f9be7-6274-4a7a-96a5-d8209d1d6cd7.png">

- User attached the photo using the 'Upload file from device' button, which then converts to an 'Upload' button to later send to the backend (integration ticket). A snack bar message pops up to signal the user the file has been received.
<img width="838" alt="after_file_input" src="https://user-images.githubusercontent.com/18078583/152598778-aca0dae5-a6fb-4205-8368-af8a09f64441.png">

### Any information needed to test this feature (required):
- Sign in with a valid user and click on the drop-down at the top right corner
- Click Settings then click the Profile photo

### Any issues with the current functionality (optional):
- The integration ticket will contain the logic to carry the file through with API helpers

2022-02-05 19:29 UTC, EdwardOlmos commented
This is a cleaner PR compared to the previously closed PR

2022-02-06 18:44 UTC, ezeilo-su requested changes
Hey @EdwardOlmos, good progress so far. Kindly take a look at the comments below and address them.
Happy coding!

2022-02-06 18:44 UTC, ezeilo-su commented on client/src/pages/Settings/ProfilePhoto/ProfilePhoto.tsx
> +  };
Please remove code if not used. Our code will be cleaner by removing unused and commented-out codes.

2022-02-06 18:44 UTC, ezeilo-su commented on client/src/pages/Settings/ProfilePhoto/ProfilePhoto.tsx
> +          <img src={`https://robohash.org/${currentUser!.email}.png`} className={classes.photo} />
These `img` tags are missing `alt` attribute.

2022-02-08 21:37 UTC, rajivtitus commented on client/src/pages/Settings/ProfilePhoto/ProfilePhoto.tsx
> +  currentProfile?: any;
Please avoid using `any` as a type. Let's use the Profile interface here instead (we can create one if it doesn't exist)

2022-02-08 21:39 UTC, rajivtitus commented on client/src/pages/Settings/ProfilePhoto/ProfilePhoto.tsx
> +          <img src={currentProfile.photo} className={classes.photo} alt="Uploaded user profile photo" />
Rather than using an HTML image element, we can use the MUI Avatar component here :)

Ref: https://mui.com/api/avatar/

2022-02-08 21:40 UTC, rajivtitus commented on client/src/pages/Settings/ProfilePhoto/useStyles.ts
> +    width: '180px',
I would recommend using relative units rather than absolute ones

Ditto throughout!

2022-02-08 21:41 UTC, rajivtitus reviewed
UI looks great 🎉 
Just some minor comments for you to address, thanks :)

2022-02-09 05:47 UTC, EdwardOlmos commented
> UI looks great 🎉 Just some minor comments for you to address, thanks :)

Thank you, @rajivtitus! Comments addressed 👍

2022-02-10 19:54 UTC, ezeilo-su commented
Please resolve merge conflicts

2022-02-11 15:47 UTC, rajivtitus approved these changes
LGTM! Good work with those changes 🎉

2022-02-11 19:52 UTC, merged