Implement Profile Listings UI on Dashboard
hatchways/team-watermint pull request #65
Opened 2022-02-16 22:37 UTC by EdwardOlmos

### What this PR does (required):
- Resolves #21
- Updates Dashboard to show Profile Listings
- Creates new Profile Card for Profile Listings
- Allows users not logged in to view the Dashboard

### Screenshots / Videos (front-end only):
- Navigate to Dashboard (/dashboard)
<img width="978" alt="chrome_DaF2QtPLXv" src="https://user-images.githubusercontent.com/18078583/154368628-49df4e64-fe5c-4132-ae38-5bc683471106.png">

### Any information needed to test this feature (required):
- Navigate to Dashboard (/dashboard)

### Any issues with the current functionality (optional):
- I can't get the date range picker to match the mock
- The integration from Landing Page to Dashboard will be addressed in the next ticket
- I plan on removing the hard-coded profiles during the integration phase

2022-02-17 20:08 UTC, ezeilo-su requested changes
Good progress with this one. I've left a comment you need to address.

2022-02-17 20:54 UTC, EdwardOlmos commented on client/src/pages/Dashboard/Dashboard.tsx
> +                  <Grid key={i} item>
@ezeilo-su Thanks for pointing that out! I used the profile id instead of indices to avoid the anti-pattern

2022-02-25 12:36 UTC, ezeilo-su reviewed
Good changes :+1:

2022-02-25 17:43 UTC, ezeilo-su reviewed
Thank you for making the requested changes

2022-02-25 17:43 UTC, ezeilo-su commented on client/src/pages/Dashboard/Dashboard.tsx
> +      <Grid key={profileCard.id} item>
:+1:

2022-02-25 20:13 UTC, rajivtitus commented on client/src/pages/Dashboard/Dashboard.tsx
> +            <LocalizationProvider dateAdapter={AdapterDateFns}>
We can move the `LocalizationProvider` to the App.tsx so that we can reuse it across the entire app 😄

2022-02-25 20:14 UTC, rajivtitus approved these changes
Great work! UI looks fantastic 🦖

2022-02-26 00:58 UTC, merged